Quizes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
path('', include('finalQuiz.urls', namespace='quizes')),
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

finalQuiz/urls.py
from django.urls import path
from . import views
from .views import QuizListView
from django.contrib.auth import views as auth_views
app_name = 'quizes'

urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('<int:pk>/', views.quiz_view, name='quiz-view'),
    path('<int:pk>/save/', views.save_quiz_view, name='save-view'),
    path('<int:pk>/data/', views.quiz_data_view, name='quiz-data-view'),
path('register/', views.register, name='register'),
path('login/', auth_views.LoginView.as_view(template_name="quizes/login.html"), name='login'),
path('logout/', auth_views.LogoutView.as_view(template_name="quizes/logout.html"), name='logout'),
]

finalQuiz/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import random
DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()

class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

finalQuiz/forms.py
from django import forms
from .models import Quiz, Question, Answer
from django.contrib import admin
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = ('name', 'topic', 'number_of_questions', 'time', 'required_score_to_pass','difficulty')

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ('text', 'quiz')

finalQuiz/views.py
from django.shortcuts import render, redirect
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from .models import Question, Answer
from .models import Result
from .forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

class QuizListView(ListView):
    model = Quiz
    template_name = 'quizes/main.html'

@login_required
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your Account has been created! you are now able to log in!')
            return redirect('quizes:login')
    else:
        form = UserRegisterForm()
    return render(request, 'quizes/register.html', {'form': form})



def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

@login_required
def save_quiz_view(request, pk):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
    #if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            try:
                question = Question.objects.get(text=k)
            except Question.DoesNotExist:
                print(f'question with text "{k}" is not found')
            questions.append(question)

        """for k in data_.keys():
            print('key: ', k)
            question = Question.objects.filter(text=k).first()
            questions.append(question)
        print(questions)"""

        #user = User.objects.get(user=User)

        user = request.user

        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})




'''
from django.shortcuts import render, redirect
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result
from choice.forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
#from django.contrib.auth.models import User

class QuizListView(ListView):
    model = Quiz
    template_name = 'quizes/main.html'

@login_required
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})


def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your Account has been created! you are now able to log in!')
            return redirect('quizes:login')
    else:
        form = UserRegisterForm()
    return render(request, 'quizes/register.html', {'form': form})


@login_required
def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            try:
                question = Question.objects.get(text=k)
            except Question.DoesNotExist:
                print(f'question with text "{k}" is not found')
            questions.append(question)

        """for k in data_.keys():
            print('key: ', k)
            question = Question.objects.filter(text=k).first()
            questions.append(question)
        print(questions)"""

        #user = User.objects.get(user=User)

        user = request.user

        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})
'''

finalQuiz/templates/quizes/base.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- Bootstrap CSS -->

 <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- custom css & js-->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app| {% block title %}{% endblock title %}</title>
  </head>
  <body>
  <nav id="navbar" class="navbar">
    <div>

		{% if user.is_authenticated %}
        <a class="nav-item nav-link" href="/">Home</a>
			<a class="nav-item nav-link" href="{% url 'quizes:logout' %}">Logout</a>

		{% else %}
        <a class="nav-item nav-link" href="/">Home</a>
<a class="nav-item nav-link" href="{% url 'quizes:login' %}">Login</a>
			<a class="nav-item nav-link" href="{% url 'quizes:register' %}">Register</a>
		{% endif %}
                </ul>
	</div>

</nav>


    <div class="container mt-3">
        {% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{message.tags}}">
					{{message}}
		</div>
			{% endfor %}
		{% endif %}
        {% block content %}
        {% endblock content %}
    </div>

 <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>  </body>
  </body>
</html>

finalQuiz/templates/quizes/login.html
{% extends 'quizes/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit" >Login</button>
          </div>

    </form>
    <div class="border-top" pt-3>
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{% url 'quizes:register' %}">Sign Up Now</a>
        </small>
    </div>
</div>
{% endblock content %}

finalQuiz/templates/quizes/logout.html
{% extends 'quizes/base.html' %}
{% block content %}
<h2>You have been logged out</h2>

    <div class="border-top" pt-3>
        <small class="text-muted">
            <a href="{% url 'quizes:login' %}">Log In Again</a>
        </small>

    </div>
 {% endblock content %}

finalQuiz/templates/quizes/main.html
{% extends "quizes/base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
Sarbee app
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
        <button type="button" id="start-button" class="btn btn-success">Yes</button>
      </div>
    </div>
  </div>
</div>
<div class="spinner-grow text-primary" role="status">

</div>
<div class="spinner-grow text-secondary" role="status">

</div>
<div class="spinner-grow text-success" role="status">

</div>
<div class="spinner-grow text-danger" role="status">

</div>
<div class="spinner-grow text-warning" role="status">

</div>
<div class="spinner-grow text-info" role="status">

</div>
<div class="spinner-grow text-success" role="status">

</div>
<div class="spinner-grow text-dark" role="status">

</div>

<div class="h4">Welcome {{user.username}} to your weekly assesment test. Give your best Good luck!!</div>
<hr>

{% for obj in object_list %}
    <button
        class="btn btn-link modal-button"
        data-pk="{{obj.pk}}"
        data-quiz="{{obj.name}}"
        data-questions="{{obj.number_of_questions}}"
        data-difficulty="{{obj.difficulty}}"
        data-time="{{obj.time}}"
        data-pass = "{{obj.required_score_to_pass}}"
        data-toggle="modal"
        data-target="#quizStartModal">
        {{obj.name}}
    </button><br>

{% endfor %}
<br/>
<br/>
<div class="instruction" >
<p text text-info><strong><i>INSTRUCTIONS:</i></strong> <br> Read your books very well before attempting the questions. The number of
questions you are to attempt will be displayed to you as an alert click on the Yes button to begin
the test. Be cautious of the time as when your time elapse the option you did not pick will be
marked as zero. When you are done with your test click on the submit button. you should scroll down to see
your result. The answer for each question will be displayed right next to it. Wishing you Goodluck...</p>
    </div>
{% endblock content %}

finalQuiz/templates/quizes/quiz.html
{% extends "quizes/base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>score to pass: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
</div>

<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">go back</a>
<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}

finalQuiz/templates/quizes/register.html
{% extends 'quizes/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit" >Sign Up</button>
        </div>
    </form>
    <div class="border-top" pt-3>
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{% url 'quizes:login' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock content %}